version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: pdf-translator-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pdf_translator
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: pdf-translator-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  server:
    build: ./server
    container_name: pdf-translator-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/pdf_translator?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: pdf-translator-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  mongodb_data:
